version: '3'
services:
  backend:
    build: ./backend
    image: backend:latest
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
  frontend:
    build: .
    image: frontend:latest
    environment:
      PORT: 3000
    ports:
      - "3000:3000"