# Generated by Django 4.1.4 on 2022-12-10 12:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0123456789'. Up to 15 digits allowed.", regex='^\\d{10,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESSFULL', 'Successfull'), ('FAILED', 'Failed')], default='FAILED', max_length=50)),
                ('batch', models.CharField(choices=[('6_7AM', 'Batch1'), ('7_8AM', 'Batch2'), ('8_9AM', 'Batch3'), ('5_6PM', 'Batch4')], default='5_6PM', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('batch_month', models.CharField(default='JANUARY', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
